[package]
name = "libshvgate-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
log = "0.4.29"
shvclient = { version = "0.22.0", default-features = false }
smol = { version = "2.0.2", optional = true }
tokio = { version = "1.49.0", optional = true }
url = "2.5.8"

[features]
default = []

tokio = ["dep:tokio", "shvclient/tokio"]
smol = ["dep:smol", "shvclient/smol"]

[dev-dependencies]
tokio = { version = "1.49.0" }
shvclient = { version = "0.22.0", features = ["tokio"] }

# [patch.crates-io]
# shvclient = { path = "../libshvclient-rs" }
